### ISSUE TITLE
Notofications

### ISSUE THREAD

**Issue by abhishekds94** [g0g0l/FChat#1]
Does this include the notification part when the app is in background? @g0g0l @Bibaswann

**Comment by g0g0l** [comment]
It is not yet implemented, I will work on that

**Comment by onyebuchiboss** [comment]
Hi, Can I use part of your code in my final year project please ?? I can not find any licensing on it, thats why I am asking.

**Comment by g0g0l** [comment]
You are free to use/modify any part of code

**Comment by achinverma** [comment]
Hi, please can you tell me how can I get the message even if my app is in the background?

**Comment by g0g0l** [comment]
I have implemented notification using JobScheduler. It might have some bugs as I didn't have time to test it thoroughly, but you will get an idea
